
# This file is automatically generated, you probably don't want to edit this

modmedOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "modmedOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            meds = NULL,
            pred = NULL,
            xmmod = NULL,
            mymod = NULL,
            covsm = NULL,
            covsy = NULL,
            estMethod = "standard",
            bootstrap = 500,
            showFit = FALSE,
            paths = FALSE,
            plotIom = FALSE,
            plotSS = FALSE, ...) {

            super$initialize(
                package='jamm',
                name='modmed',
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..meds <- jmvcore::OptionVariables$new(
                "meds",
                meds,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..pred <- jmvcore::OptionVariable$new(
                "pred",
                pred,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..xmmod <- jmvcore::OptionVariable$new(
                "xmmod",
                xmmod,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..mymod <- jmvcore::OptionVariable$new(
                "mymod",
                mymod,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..covsm <- jmvcore::OptionVariables$new(
                "covsm",
                covsm,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..covsy <- jmvcore::OptionVariables$new(
                "covsy",
                covsy,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..estMethod <- jmvcore::OptionList$new(
                "estMethod",
                estMethod,
                options=list(
                    "standard",
                    "bootstrap"),
                default="standard")
            private$..bootstrap <- jmvcore::OptionInteger$new(
                "bootstrap",
                bootstrap,
                min=1,
                default=500)
            private$..showFit <- jmvcore::OptionBool$new(
                "showFit",
                showFit,
                default=FALSE)
            private$..paths <- jmvcore::OptionBool$new(
                "paths",
                paths,
                default=FALSE)
            private$..plotIom <- jmvcore::OptionBool$new(
                "plotIom",
                plotIom,
                default=FALSE)
            private$..plotSS <- jmvcore::OptionBool$new(
                "plotSS",
                plotSS,
                default=FALSE)

            self$.addOption(private$..dep)
            self$.addOption(private$..meds)
            self$.addOption(private$..pred)
            self$.addOption(private$..xmmod)
            self$.addOption(private$..mymod)
            self$.addOption(private$..covsm)
            self$.addOption(private$..covsy)
            self$.addOption(private$..estMethod)
            self$.addOption(private$..bootstrap)
            self$.addOption(private$..showFit)
            self$.addOption(private$..paths)
            self$.addOption(private$..plotIom)
            self$.addOption(private$..plotSS)
        }),
    active = list(
        dep = function() private$..dep$value,
        meds = function() private$..meds$value,
        pred = function() private$..pred$value,
        xmmod = function() private$..xmmod$value,
        mymod = function() private$..mymod$value,
        covsm = function() private$..covsm$value,
        covsy = function() private$..covsy$value,
        estMethod = function() private$..estMethod$value,
        bootstrap = function() private$..bootstrap$value,
        showFit = function() private$..showFit$value,
        paths = function() private$..paths$value,
        plotIom = function() private$..plotIom$value,
        plotSS = function() private$..plotSS$value),
    private = list(
        ..dep = NA,
        ..meds = NA,
        ..pred = NA,
        ..xmmod = NA,
        ..mymod = NA,
        ..covsm = NA,
        ..covsy = NA,
        ..estMethod = NA,
        ..bootstrap = NA,
        ..showFit = NA,
        ..paths = NA,
        ..plotIom = NA,
        ..plotSS = NA)
)

modmedResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        rsq = function() private$.items[["rsq"]],
        apaths = function() private$.items[["apaths"]],
        bpaths = function() private$.items[["bpaths"]],
        indirectEffect = function() private$.items[["indirectEffect"]],
        directEffect = function() private$.items[["directEffect"]],
        indirectEffectStand = function() private$.items[["indirectEffectStand"]],
        plotIMMx = function() private$.items[["plotIMMx"]],
        plotIMMy = function() private$.items[["plotIMMy"]],
        plotSSx = function() private$.items[["plotSSx"]],
        plotSSy = function() private$.items[["plotSSy"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Moderated Mediation")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Model fit",
                visible="(showFit)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="rsq",
                title="Explained variances",
                rows="(c(meds,dep))",
                columns=list(
                    list(
                        `name`="varName", 
                        `title`="", 
                        `content`="($key)", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="R square", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="apaths",
                title="a paths",
                rows="(length(meds) + 2*length(xmmod)*length(meds))",
                visible="(paths)",
                columns=list(
                    list(
                        `name`="varName", 
                        `title`="effect  ", 
                        `type`="text"),
                    list(
                        `name`="est", 
                        `title`="estimate", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="se", 
                        `type`="number"),
                    list(
                        `name`="z", 
                        `title`="z", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto, pvalue"),
                    list(
                        `name`="ci.lower", 
                        `title`="ci.lower", 
                        `type`="number"),
                    list(
                        `name`="ci.upper", 
                        `title`="ci.upper", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="bpaths",
                title="b paths",
                rows="(length(meds)+(length(mymod)*length(meds))+(length(mymod)*1))",
                visible="(paths)",
                columns=list(
                    list(
                        `name`="varName", 
                        `title`="effect  ", 
                        `type`="text"),
                    list(
                        `name`="est", 
                        `title`="estimate", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="se", 
                        `type`="number"),
                    list(
                        `name`="z", 
                        `title`="z", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto, pvalue"),
                    list(
                        `name`="ci.lower", 
                        `title`="ci.lower", 
                        `type`="number"),
                    list(
                        `name`="ci.upper", 
                        `title`="ci.upper", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="indirectEffect",
                title="Indirect effects",
                rows="(c(meds,\"total\"))",
                columns=list(
                    list(
                        `name`="varName", 
                        `title`="Mediator", 
                        `content`="($key)", 
                        `type`="text"),
                    list(
                        `name`="est", 
                        `title`="estimate", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="se", 
                        `type`="number"),
                    list(
                        `name`="z", 
                        `title`="z", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto, pvalue"),
                    list(
                        `name`="ci.lower", 
                        `title`="ci.lower", 
                        `type`="number"),
                    list(
                        `name`="ci.upper", 
                        `title`="ci.upper", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="directEffect",
                title="Direct effects",
                rows="(pred)",
                columns=list(
                    list(
                        `name`="varName", 
                        `title`="", 
                        `content`="($key)", 
                        `type`="text"),
                    list(
                        `name`="est", 
                        `title`="estimate", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="se", 
                        `type`="number"),
                    list(
                        `name`="z", 
                        `title`="z", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto, pvalue"),
                    list(
                        `name`="ci.lower", 
                        `title`="ci.lower", 
                        `type`="number"),
                    list(
                        `name`="ci.upper", 
                        `title`="ci.upper", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="indirectEffectStand",
                title="Standardized indirect effects",
                rows="(meds)",
                columns=list(
                    list(
                        `name`="varName", 
                        `title`="Mediator", 
                        `content`="($key)", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Standardized indirect effect", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotIMMx",
                title="Index of moderated mediation x-m path",
                visible="(plotIom)",
                width=600,
                height=450,
                renderFun=".plotIom"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotIMMy",
                title="Index of moderated mediation m-y path",
                visible="(plotIom)",
                width=600,
                height=450,
                renderFun=".plotIom"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotSSx",
                title="Simple slopes for moderator x-m path",
                visible="(plotSS)",
                width=600,
                height=450,
                renderFun=".plotSS"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotSSy",
                title="Simple slopes for moderator m-y path",
                visible="(plotSS)",
                width=600,
                height=450,
                renderFun=".plotSS"))}))

modmedBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "modmedBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'jamm',
                name = 'modmed',
                version = c(1,0,0),
                options = options,
                results = modmedResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Moderated Mediation
#'
#' 
#' @param data the data as a data frame
#' @param dep a string naming the dependent variable
#' @param meds a string naming the mediator variable
#' @param pred a string naming the predictor variable
#' @param xmmod a string naming the predictor variable
#' @param mymod a string naming the predictor variable
#' @param covsm a vector with strings naming the covariates
#' @param covsy a vector with strings naming the covariates
#' @param estMethod \code{'standard'} (default), or \code{'bootstrap'}, the
#'   estimation method to use
#' @param bootstrap a number between 1 and 100000 (default: 1000) specifying
#'   the number of samples that need to been drawn in the bootstrap method
#' @param showFit \code{TRUE} or \code{FALSE} (default), provides the lavaan
#'   fit values of the  the mediation model
#' @param paths \code{TRUE} or \code{FALSE} (default), provide the individual
#'   estimates of the a and b paths in the mediation model
#' @param plotIom \code{TRUE} (default) or \code{FALSE}, provides 'plot
#'   showing the index  of mediation for each mediator and moderator
#' @param plotSS \code{TRUE} or \code{FALSE} (default), provides a simple
#'   slope plot where for each mediator the estimated simple slopes are plotted.
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$rsq} \tab \tab \tab \tab \tab a table containing the explained variances \cr
#'   \code{results$apaths} \tab \tab \tab \tab \tab a table containing the a paths \cr
#'   \code{results$bpaths} \tab \tab \tab \tab \tab a table containing the b paths \cr
#'   \code{results$indirectEffect} \tab \tab \tab \tab \tab a table containing the indirect effects \cr
#'   \code{results$directEffect} \tab \tab \tab \tab \tab a table containing the Direct effects \cr
#'   \code{results$indirectEffectStand} \tab \tab \tab \tab \tab a table containing the Standardized indirect effects \cr
#'   \code{results$plotIMMx} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotIMMy} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotSSx} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotSSy} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$rsq$asDF}
#'
#' \code{as.data.frame(results$rsq)}
#'
#' @export
modmed <- function(
    data,
    dep,
    meds,
    pred,
    xmmod,
    mymod,
    covsm,
    covsy,
    estMethod = "standard",
    bootstrap = 500,
    showFit = FALSE,
    paths = FALSE,
    plotIom = FALSE,
    plotSS = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('modmed requires jmvcore to be installed (restart may be required)')

    if (missing(data))
        data <- jmvcore:::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(meds), meds, NULL),
            `if`( ! missing(pred), pred, NULL),
            `if`( ! missing(xmmod), xmmod, NULL),
            `if`( ! missing(mymod), mymod, NULL),
            `if`( ! missing(covsm), covsm, NULL),
            `if`( ! missing(covsy), covsy, NULL))

    options <- modmedOptions$new(
        dep = dep,
        meds = meds,
        pred = pred,
        xmmod = xmmod,
        mymod = mymod,
        covsm = covsm,
        covsy = covsy,
        estMethod = estMethod,
        bootstrap = bootstrap,
        showFit = showFit,
        paths = paths,
        plotIom = plotIom,
        plotSS = plotSS)

    results <- modmedResults$new(
        options = options)

    analysis <- modmedClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
